config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root "tweets#index"
  resources :tweets do
    resources :comments, only: [:create]
  end
  resources :users, only: [:show]
end

app/models/comment.rb
class Comment < ActiveRecord::Base
    belongs_to :user
  belongs_to :tweet
end

app/models/tweet.rb
class Tweet < ActiveRecord::Base

  belongs_to :user
  has_many :comments

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  validates :nickname, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

   before_action :configure_permitted_parameters, if: :devise_controller?

    def configure_permitted_parameters
      devise_parameter_sanitizer.permit(:sign_up, keys: [:nickname])
    end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  def create
    @comment = Comment.create(text: comment_params[:text], tweet_id: comment_params[:tweet_id], user_id: current_user.id)
    redirect_to "/tweets"
  end

  private
  def comment_params
    params.require(:comment).permit(:text).merge(tweet_id: params[:tweet_id])
  end

end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController

  before_action :move_to_index, except: :index

  def index
    @tweets = Tweet.all.order("created_at DESC")
  end

  def show
    @tweet = Tweet.find(params[:id])
    @comment = Comment.new
    @comments = @tweet.comments.includes(:user)
  end

  def new
    @tweet = Tweet.new
  end

  def create
    Tweet.create(user_id: current_user.id, text: tweet_params[:text])
  end

  def destroy
    @tweet = Tweet.find(params[:id])
    if @tweet.user_id == current_user.id
      @tweet.destroy
    end
  end

  def edit
    @tweet = Tweet.find(params[:id])
  end

  def update
    tweet = Tweet.find(params[:id])
    if tweet.user_id == current_user.id
      tweet.update(tweet_params)
    end
  end

  private
  def tweet_params
    params.require(:tweet).permit(:text)
  end

  def move_to_index
    redirect_to action: :index unless user_signed_in?
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def show
    user = User.find(params[:id])
    @nickname = current_user.nickname
    @tweets = Tweet.where(user_id: current_user.id).order("created_at DESC")
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Murphy</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<!-- boootstrap導入部分 -->
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbarEexample1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/"><strong>Murphy</strong></a>
    </div>
    <div class="collapse navbar-collapse" id="navbarEexample1">
      <% if user_signed_in? %>
        <span><strong><%= current_user.nickname %>さん</strong>
          <ul class="nav navbar-nav">
            <li><a class="post" href="/tweets/new">投稿する</a></li>
            <li><a href="/users/<%= current_user.id%>">マイページ</a></li>
            <li><%= link_to "ログアウト", destroy_user_session_path, method: :delete %></a></li>
          </ul>
        </span>
      <% else %>
        <span>
          <ul class="nav navbar-nav">
            <li><%= link_to "ログイン", new_user_session_path, class: 'post' %></li>
            <li><%= link_to "新規登録", new_user_registration_path, class: 'post' %></li>
          </ul>
        </span>
      <% end %>
    </div>
  </div>
</nav>


<%= yield %>

</body>
</html>

app/views/tweets/_form.html.erb
<div class="contents">
  <%= form_for [@tweet] do |f| %>
    <div style="margin: 8px 0">
      <%= f.text_area :text, placeholder: 'テキスト', style: 'width: 90%;height: 100px;' %>
    </div>
    <div class="row">
      <div class="col10 push1">
        <%= button_tag type: "submit", class: "btn btn--block" do %>
          送信<i class="icon-arrow-right"></i>
        <% end %>
      </div>
    </div>
  <% end %>
</div>

app/views/tweets/create.html.erb
<div class="contents row">
  <div class="success">
    <h3>投稿しました！</h3>
    <a class="btn", href="/tweets">ホームに戻る</a>
  </div>
</div>

app/views/tweets/destroy.html.erb
<div class="contents row">
    <div class="success">
      <h3>
        削除が完了しました。
      </h3>
      <a class="btn" href="/">投稿一覧へ戻る</a>
    </div>
  </div>

app/views/tweets/edit.html.erb
<h3>編集する</h3>
  <%= render "form" %>

app/views/tweets/index.html.erb
<div class="contents" >
  <% @tweets.each do |tweet| %>
    <div class="balloon1-right col-sm-6 col-sm-offset-3">
        <p><%= simple_format(tweet.text) %></p>
          <span class="name">
              <%= tweet.user.nickname %>さん
          </span>
      <div class="btn-group">
        <button type="button" class="btn btn-info dropdown-toggle" data-toggle="dropdown" aria-expanded="false">
          action
          <span class="caret"></span>
        </button>
          <ul class="dropdown-menu" role="menu">
              <li role="presentation"><%= link_to 'コメント', tweet_path(tweet) , method: :get %></li>
            <% if user_signed_in? && current_user.id == tweet.user_id %>
              <li role="presentation"><%= link_to '編集', edit_tweet_path(tweet) , method: :get %></a></li>
              <li role="presentation"><%= link_to '削除', "/tweets/#{tweet.id}", method: :delete %></a></li>
          </ul>
            <% end %>
      </div>
    </div>
  <% end %>
</div>

app/views/tweets/new.html.erb
<h3>投稿する</h3>
  <%= render "form" %>

app/views/tweets/show.html.erb
<div class="contents">
  <div class="content-post">
    <% if user_signed_in? && current_user.id == @tweet.user_id %>
      <div class="more">
        <ul class="more list">
      </div>
    <% end %>
    <%= simple_format(@tweet.text) %>
    <span class="name">
      <a href="/users/<%= @tweet.user.id %>">
        <span>投稿者</span><%= @tweet.user.nickname %>
      </a>
    </span>
  </div>
  <div class="container">
    <% if current_user %>
      <%= form_for [@tweet, @comment] do |f| %>
        <div class="row">
          <div class="col10 push1">
          <%= f.text_area :text, placeholder: 'テキスト', style: 'width: 90%;height: 100px;' %>
          <%= button_tag type: "submit", class: "btn btn--block" do %>送信<i class="icon-arrow-right"></i>
          <% end %>
      <% end %>
    <% end %>
    <div class="comments">
      <h4>＜コメント一覧＞</h4>
      <% if @comments %>
        <% @comments.each do |comment| %>
          <p>
            <strong><%= link_to comment.user.nickname, "/users/#{comment.user_id}" %>：</strong>
            <%= comment.text %>
          </p>
        <% end %>
      <% end %>
    </div>
  </div>
</div>

app/views/tweets/update.html.erb
<div class="contents row">
    <div class="success">
      <h3>
        編集が完了しました。
      </h3>
      <a class="btn" href="/">投稿一覧へ戻る</a>
    </div>
  </div>

app/views/users/show.html.erb
<div class="contents row">
  <p><%= @nickname %>さんの投稿</p>
    <% @tweets.each do |tweet| %>
      <div class="balloon1-right col-sm-6 col-sm-offset-3">
        <div class="content_post">
          <%= simple_format(tweet.text) %>
        </div>
      </div>
    <% end %>
</div>